### ISSUE TITLE
Cu subnetwork

### ISSUE THREAD

**Issue by alliegu** [Dexterp37/fontina#10]
Hi! Testing this implementation on real images and trying to figure out if I can improve performance. In the paper they mention that Layers 1 and 2 are imported to the CNN in Fig. 5, as the **Cu** sub-network and fixed. But in the implementation you seem to call the full autoencoder upon training the full network. I wonder if that was intentional? Thanks!
Edit: nevermind, it's just the encoder

**Comment by alliegu** [comment]
Oh nevermind, it's just the encoder

**Comment by Dexterp37** [comment]
> Oh nevermind, it's just the encoder

No worries! Please let me know if you need further explanation. If you manage to find out what the problem is, I'm willing to spend GPU time to retrain this and share the checkpoints.

**Comment by alliegu** [comment]
Can I ask what python / pytorch / torchvision versions you're using? I did the installation steps but ran into versioning issues; downgraded and new issues popped up. Thank you so much!

**Comment by Dexterp37** [comment]
> Can I ask what python / pytorch / torchvision versions you're using? I did the installation steps but ran into versioning issues; downgraded and new issues popped up. Thank you so much!

Whops, sorry I missed this reply. @alliegu I'm using Python 3.10, torch 2.0.1 and the related torchvision version. See [here](https://github.com/Dexterp37/fontina/blob/541beed50773e963489ab186a5e9c480640ffb09/pyproject.toml#L16).

**Comment by anruigu** [comment]
Just wanted to comment that with your pretrained full checkpoint, even though I couldn't reproduce correct predictions using test samples in the paper, this is a sufficiently good feature extractor for my use case on unlabeled fonts. Really appreciate it!

**Comment by Dexterp37** [comment]
> Just wanted to comment that with your pretrained full checkpoint, even though I couldn't reproduce correct predictions using test samples in the paper, this is a sufficiently good feature extractor for my use case on unlabeled fonts. Really appreciate it!

@anruigu I'm glad you found this helpful! Keep up the great work!
