### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by zemmsoares** [Dexterp37/fontina#11]
Thanks for the code!
I've been trying to train my data but so far no success. I always encounter one of the following errors:

`RuntimeError: stack expects each tensor to be equal size, but got [105, 262] at entry 0 and [105, 1065] at entry 1`

`AttributeError:  'numpy.ndarray' object has no attribute 'unsqueeze'. Did you mean: 'squeeze'?`

Any ideas what could be causing these issues?

**Comment by zemmsoares** [comment]
Ok managed to fix it :fire:

**Comment by Dexterp37** [comment]
> Ok managed to fix it 🔥

I'm glad! Let me know if further help is needed!
